apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  sources:
    - repoURL: https://github.com/rklonner/argocd-diff-preview
      ref: local-files
    - path: examples/use-cases/refactor-helm-per-env-to-central-chart/my-app/my-app
      repoURL: https://github.com/rklonner/argocd-diff-preview
      helm:
        valueFiles:
          - $local-files/examples/use-cases/refactor-helm-per-env-to-central-chart/my-app/values/dev.yaml
